### ISSUE TITLE
The plugin is showing country code instead of Flag Emoji

### ISSUE THREAD

**Issue by sooxt98** [stidges/country-flags#1]

**Comment by stidges** [comment]
Can you give more information about what country code you are trying to use?

**Comment by sooxt98** [comment]
MY, I think the problem is related to production settings, it works fine on local

**Comment by stidges** [comment]
I cannot reproduce this on my machine either, it's not showing up in the browser on production?

**Comment by sooxt98** [comment]
![image](https://user-images.githubusercontent.com/13378059/79735771-5fa98900-832b-11ea-8d3f-6df9a1ce4c2c.png)

**Comment by stidges** [comment]
What font stack are you using? It may be that the fonts don't support emoji

**Comment by sooxt98** [comment]
I tried on Mac iOS and windows, all can’t

**Comment by stidges** [comment]
It depends on the font you are using in your CSS styles, if that font does not support emoji it won't show up

**Comment by sooxt98** [comment]
ahhhh i think is just doesnt work on windows, do you know any alternative ways to solve this?

**Comment by stidges** [comment]
Make sure you have the system emoji fonts in your font stack as fallback in CSS, e.g.

```css
html {
  font-family: "your font stack...", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```
